# default DB properties:
spring:
  datasource:
    allowMultiQueries: true
    default:
      url: jdbc:mysql://localhost:3306/master?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: comondao
  jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 80

#mybatis:
#      configuration:
#          map-underscore-to-camel-case: true
#      mapper-locations: mapper/*Mapper.xml



